services:
  authsvc:
    build: .
    image: google-auth-service:latest
    container_name: google-auth-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
